(function(){
if(typeof L==='undefined'||typeof map==='undefined')return;
const layer=L.layerGroup().addTo(map);const C={after:'#4aa3ff',swarm:'#d66bff',mixed:'#ffb347',iso:'#9aa7b4'};
function fam(e){try{return tectonicFamily(e)}catch(_){if(e.depth>=70)return'intraslab';if(e.depth>=30)return'intermediate';if(e.lon<=-79.6)return'interface';return'cortical'}}
function chocoSwarm(e){return e.lat>=3.5&&e.lat<=5.5&&e.lon>=-77.8&&e.lon<=-76.0&&e.depth>=20&&e.depth<=65}
function chocoDeep(e){return e.lat>=3.5&&e.lat<=5.6&&e.lon>=-77.8&&e.lon<=-75.6&&e.depth>=70&&e.depth<=120}
function parentScore(c,p){if(p.time>=c.time||p.mag<c.mag+0.5)return 0;const dt=(c.time-p.time)/86400000;if(dt>21)return 0;const r=p.mag>=7?350:p.mag>=6?250:p.mag>=5?160:90;const d=distKm(c.lat,c.lon,p.lat,p.lon);if(d>r)return 0;const dz=Math.abs((c.depth||0)-(p.depth||0));if(fam(c)!==fam(p)&&dz>25)return 0;if(dz>45)return 0;return 100*(.38*(1-d/r)+.27*(1-dt/21)+.20*Math.min(1,(p.mag-c.mag)/2)+.15*(1-dz/45))}
function clusters(events){const out=[];for(const e of events){let b=null;for(const c of out){if(c.family!==fam(e))continue;const d=distKm(e.lat,e.lon,c.lat,c.lon);if(d<=80&&(!b||d<b.d))b={c,d}}if(!b)out.push({family:fam(e),events:[e],lat:e.lat,lon:e.lon});else{b.c.events.push(e);const n=b.c.events.length;b.c.lat=(b.c.lat*(n-1)+e.lat)/n;b.c.lon=(b.c.lon*(n-1)+e.lon)/n}}return out}
function card(){if(document.getElementById('sequenceCard35'))return;const a=document.querySelector('aside');if(!a)return;const s=document.createElement('section');s.className='card';s.id='sequenceCard35';s.innerHTML='<h2>🧭 Réplicas vs enjambres</h2><div class="kpis"><div class="kpi"><div class="name">Réplicas probables</div><div class="val" id="s35a">—</div></div><div class="kpi"><div class="name">Eventos en enjambre</div><div class="val" id="s35s">—</div></div><div class="kpi"><div class="name">Zonas enjambre</div><div class="val" id="s35z">—</div></div><div class="kpi"><div class="name">Mixtos / aislados</div><div class="val" id="s35i">—</div></div></div><div id="s35txt" class="small" style="margin-top:8px"></div><div class="small" style="margin-top:8px;color:#7894ac"><b>Regla Chocó:</b> eventos de ~20–65 km en Sipí–Istmina–Medio/Litoral del San Juan se tratan como población de enjambre, separada de las réplicas profundas ~70–105 km de San José del Palmar, siguiendo la interpretación oficial del SGC. Enjambre no significa que vaya a ocurrir un sismo mayor.</div>';const z=[...document.querySelectorAll('section.card h2')].find(h=>/Zonas activas priorizadas/.test(h.textContent));z?z.parentElement.insertAdjacentElement('afterend',s):a.appendChild(s)}
function dot(e,t,reason){const col=t==='after'?C.after:t==='swarm'?C.swarm:t==='mixed'?C.mixed:C.iso;L.circleMarker([e.lat,e.lon],{radius:Math.max(4,Math.min(10,3+(e.mag-2)*1.8)),weight:2,color:col,fillColor:col,fillOpacity:.72}).bindPopup('<b>'+(t==='after'?'Réplica probable':t==='swarm'?'Enjambre probable':t==='mixed'?'Mixto/incierto':'Aislado')+'</b><br>M'+e.mag.toFixed(1)+' · '+Math.round(e.depth||0)+' km<br>'+reason).addTo(layer)}
function run(){card();let ev=[];try{ev=Array.isArray(allEvents)?allEvents:[]}catch(_){return}if(!ev.length)return;const now=Date.now(),pool=ev.filter(e=>e.time>=now-7*86400000&&e.mag>=2.0&&e.lat>=-35&&e.lat<=20&&e.lon>=-111&&e.lon<=-70).sort((a,b)=>a.time-b.time);const recent=pool.filter(e=>e.time>=now-72*3600000);layer.clearLayers();let na=0,ns=0,ni=0;const type=new Map();
for(const e of recent){if(chocoSwarm(e)){type.set(e,'swarm');continue}let best=0;for(const p of pool){const s=parentScore(e,p);if(s>best)best=s}type.set(e,best>=68?'after':'iso')}
for(const c of clusters(recent.filter(e=>!chocoSwarm(e)))){if(c.events.length<3)continue;const m=c.events.map(e=>e.mag).sort((a,b)=>b-a),dom=m[0]-(m[1]??m[0]);const ordered=c.events.slice().sort((a,b)=>a.time-b.time),mx=m[0],idx=ordered.findIndex(e=>e.mag===mx),early=idx>=0&&idx<=Math.max(1,Math.floor(ordered.length*.3));if(!(mx>=5&&dom>=1&&early)&&dom<1){for(const e of c.events){if(type.get(e)==='after')type.set(e,'mixed');else type.set(e,'swarm')}}}
let zoneKeys=new Set();for(const e of recent){const t=type.get(e)||'iso';if(t==='after'){na++;dot(e,t,'Compatible espacio-tiempo-profundidad con un evento mayor previo.')}else if(t==='swarm'){ns++;if(chocoSwarm(e))zoneKeys.add('choco');else zoneKeys.add(Math.round(e.lat*2)+':'+Math.round(e.lon*2));dot(e,t,chocoSwarm(e)?'Población somera-intermedia del enjambre de Chocó reconocido por SGC; separada de las réplicas profundas.':'Clúster sin mainshock claramente dominante.')}else{ni++;dot(e,t,'No cumple criterio suficiente de réplica o enjambre.')}}
// Contexto oficial: zona de enjambre Chocó reconocida por SGC, aunque el feed del visor no contenga todos los eventos pequeños.
L.circle([4.55,-76.75],{radius:115000,color:C.swarm,weight:2,dashArray:'6,5',fillColor:C.swarm,fillOpacity:.03}).bindTooltip('Chocó · zona de enjambre reconocida por SGC').addTo(layer);zoneKeys.add('choco');
document.getElementById('s35a').textContent=na;document.getElementById('s35s').textContent=ns;document.getElementById('s35z').textContent=zoneKeys.size;document.getElementById('s35i').textContent=ni;const ch=recent.filter(chocoSwarm);document.getElementById('s35txt').innerHTML='<b>Chocó:</b> '+ch.length+' eventos del catálogo cargado caen actualmente en la población 20–65 km; el SGC mantiene esta población como enjambre independiente de las réplicas profundas. Si el número es menor que el reportado por SGC, la limitación es del feed agregado del visor, no de la clasificación geológica.'}
card();try{L.control.layers({}, {'Secuencias · réplicas vs enjambres v35':layer},{collapsed:true,position:'topleft'}).addTo(map)}catch(_){}setTimeout(run,2000);setInterval(run,60000);const b=document.getElementById('refresh');if(b)b.addEventListener('click',()=>setTimeout(run,1800));})();