(function(){
if(typeof L==='undefined'||typeof map==='undefined')return;
const rep=L.layerGroup().addTo(map), enj=L.layerGroup().addTo(map), ind=L.layerGroup();
let last='';
function h(ms){return ms/3600000}
function rad(m){return Math.max(30,Math.min(280,3*Math.pow(10,-3.55+0.74*m)))}
function parentOf(e,evs){let best=null;for(const p of evs){if(p.time>=e.time||p.mag<5||p.mag<e.mag+0.25)continue;const dt=h(e.time-p.time);if(dt>168)continue;const d=distKm(e.lat,e.lon,p.lat,p.lon),r=rad(p.mag);if(d>r)continue;const tol=Math.max(25,0.35*Math.max(1,p.depth||0));if(Math.abs((e.depth||0)-(p.depth||0))>tol)continue;const s=100*(0.4*Math.exp(-d/Math.max(20,r*0.6))+0.3*Math.exp(-dt/72)+0.3*Math.min(1,(p.mag-e.mag)/2));if(s>=45&&(!best||s>best.score))best={p,score:s,d,dt};}return best}
function swarms(list){const out=new Map(),used=new Set();let id=0;for(const seed of list){if(used.has(seed))continue;const q=[seed],c=[];used.add(seed);while(q.length){const a=q.shift();c.push(a);for(const b of list){if(used.has(b)||Math.abs(a.time-b.time)>72*3600000||distKm(a.lat,a.lon,b.lat,b.lon)>75)continue;if(typeof tectonicFamily==='function'&&tectonicFamily(a)!==tectonicFamily(b))continue;used.add(b);q.push(b)}}const mags=c.map(x=>x.mag).sort((a,b)=>b-a);if(c.length>=4&&(mags[0]-mags[1])<=1){id++;c.forEach(e=>out.set(e,{id,count:c.length,max:mags[0],gap:mags[0]-mags[1]}))}}return out}
function card(){if(document.getElementById('seqCard'))return;const a=document.querySelector('aside');if(!a)return;const c=document.createElement('section');c.className='card';c.id='seqCard';c.innerHTML='<h2>Tipo probable de secuencia</h2><div class="kpis"><div class="kpi"><div class="name">Réplicas probables</div><div class="val" id="repN">—</div></div><div class="kpi"><div class="name">Enjambre probable</div><div class="val" id="enjN">—</div></div><div class="kpi"><div class="name">No clasificados</div><div class="val" id="indN">—</div></div></div><div id="seqTxt" class="small" style="margin-top:8px">Calculando…</div><div class="small" style="margin-top:8px;color:#7894ac">Azul = réplica probable de un evento mayor previo. Magenta = clúster/enjambre probable sin evento dominante. Gris = no clasificado. Es una clasificación experimental: un enjambre no implica necesariamente un sismo mayor y una réplica tampoco excluye un evento posterior mayor.</div>';const z=[...document.querySelectorAll('section.card h2')].find(x=>/Zonas activas/.test(x.textContent));z?z.parentElement.insertAdjacentElement('afterend',c):a.appendChild(c)}
function ring(e,color,label,txt,layer,dash){const m=L.circleMarker([e.lat,e.lon],{radius:Math.max(6,3+e.mag*1.3),weight:2.2,color,fillColor:color,fillOpacity:.04,dashArray:dash||null});m.bindPopup('<b>'+label+'</b><br>M'+e.mag.toFixed(1)+' · '+Math.round(e.depth||0)+' km<br>'+txt);m.addTo(layer)}
function run(){card();if(typeof allEvents==='undefined'||!allEvents.length)return;const cut=Date.now()-7*86400000,evs=allEvents.filter(e=>e.time>=cut&&e.mag>=2.5&&e.lat>=-35&&e.lat<=20&&e.lon>=-111&&e.lon<=-70).sort((a,b)=>a.time-b.time);const sig=evs.length+'|'+(evs.at(-1)?.time||0);if(sig===last)return;last=sig;const am=new Map(),u=[];for(const e of evs){const x=parentOf(e,evs);x?am.set(e,x):u.push(e)}const sm=swarms(u);rep.clearLayers();enj.clearLayers();ind.clearLayers();let nr=0,ns=0,ni=0,ids=new Set();for(const e of evs){if(am.has(e)){nr++;const x=am.get(e);ring(e,'#55a7ff','Réplica probable','Confianza '+x.score.toFixed(0)+'/100 · padre candidato M'+x.p.mag.toFixed(1)+' · '+Math.round(x.dt)+' h · '+Math.round(x.d)+' km',rep)}else if(sm.has(e)){ns++;const s=sm.get(e);ids.add(s.id);ring(e,'#ff62d0','Enjambre probable','Clúster '+s.id+' · '+s.count+' eventos · Mmáx '+s.max.toFixed(1),enj,'2,3')}else{ni++;ring(e,'#9aa7b3','No clasificado','No cumple criterios actuales de réplica ni enjambre.',ind,'3,5')}}document.getElementById('repN').textContent=nr;document.getElementById('enjN').textContent=ns;document.getElementById('indN').textContent=ni;document.getElementById('seqTxt').innerHTML='Últimos 7 días · M≥2.5: <b>'+evs.length+'</b> eventos · <b>'+ids.size+'</b> clúster(es) tipo enjambre.'}
card();try{L.control.layers({}, {'Secuencia · Réplicas probables':rep,'Secuencia · Enjambres probables':enj,'Secuencia · No clasificados':ind},{collapsed:true,position:'topright'}).addTo(map)}catch(e){}
setTimeout(run,2500);setInterval(run,30000);const b=document.getElementById('refresh');if(b)b.addEventListener('click',()=>setTimeout(()=>{last='';run()},2500));window.mivigeSequenceClassify=()=>{last='';run()};
})();